apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:   
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: akshpawardocker/tomcat:10.0.0
        name: hello-world
        ports:
        - containerPort: 8080
   
