apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec: 
  containers:
     - name: nodeapp
      image: akshpawardocker/samplewebapp:latest
      ports:
        - containerPort: 8080
