apiVersion: v1
kind: Service
metadata: 
  name: nodeapp
spec:
  type: LoadBalancer
  externalIPs:
    - 3.39.195.184
  selector:
    app: nodeapp
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 8080
  
